name: Deploy CoratiaOS Extension Image

on:
  push:
  # Run manually
  workflow_dispatch:
  # NOTE: caches may be removed if not run weekly
  #  -> may be worth scheduling for every 6 days

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t water-linked-dvl:latest .
      # Note: To enable Docker push, configure DOCKER_USERNAME and DOCKER_PASSWORD secrets
      # - name: Push to Docker Registry
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/water-linked-dvl:latest
